# Generated by Django 5.0.3 on 2024-05-01 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DersTalepleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_notu', models.TextField(max_length=200)),
                ('talep_durumu', models.BooleanField(default=False)),
                ('min_butce', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_butce', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('ogrenci_seviyesi', models.CharField(choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yukseklisans', 'Yüksek Lisans')], max_length=50)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.ders')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
