# Generated by Django 5.0.3 on 2024-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derstalepleri',
            name='isim',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
