# Generated by Django 5.0.3 on 2024-05-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_dil_alter_derstalepleri_talep_notu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verilebilecekdersler',
            old_name='ucret',
            new_name='saatlik_ucret',
        ),
    ]
