# Generated by Django 5.0.3 on 2024-05-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_rename_ucret_verilebilecekdersler_saatlik_ucret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='derstalepleri',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('içerik', models.TextField(max_length=200)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alınan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('gönderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gönderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
